spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # automatycznie tworzy tabele
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: auth-service
server:
  port: 8081
